[package]
name = "yaru"
version = "0.2.3"
edition = "2021"
authors = ["u2gilles <u2gilles@example.com>"]
description = "Yet Another Rust Util - A collection of utilities for timing, memory inspection and SQL result formatting."
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/u2gilles/yaru"
keywords = ["memory", "pointer", "debugging", "sql", "timing"]
categories = ["development-tools::debugging", "development-tools::profiling"]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
comfy-table = { version = "7.1", default-features = false }
